image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn && abtnode init -f --mode debug --no-https
    command: abtnode start && abtnode dev
ports:
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
