name: Npm deployment

on:
  push:
    branches:
      - main

jobs:
  Deploy:

    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Init
      run: make github-init

    - name: Deploy
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
      run: bash ./scripts/publish.sh

    - name: Release to Github
      uses: blocklet/action-release-to-github@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
