name: Blocklet workflow

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set yarn cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Init
        run: make github-init

      - name: Blocklet workflow
        uses: blocklet/action-workflow@v0.2.2
        with:
          bundle-command: yarn bundle
          github-token: ${{ secrets.GITHUB_TOKEN }}
